# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: 'ruby:2.4.2'
#
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - postgres:latest

variables:
  POSTGRES_DB: pyzlnar_test

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v                                   # Print out ruby version for debugging
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

# Rubocop setup
rubocop:
  script:
    - rubocop

# Rspec setup
rspec:
  variables:
    DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB'
  script:
    - cp config/secrets.example.yml config/secrets.yml
    - bundle exec rake db:migrate:reset
    - rspec spec
