Metrics/LineLength:
  Max: 100

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Capfile'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
