AllCops:
  TargetRubyVersion: 2.4.2
  Include:
    - '**/Gemfile'
    - '**/Capfile'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false
